require('dotenv').config()
const express = require('express')
var bodyParser = require('body-parser')
const app = express()
const api = require('./router/api')
app.use( bodyParser.json() )
app.use('/api', api)
app.use('/public', express.static(__dirname + '/public'))
app.use('', express.static(__dirname + '/client/dist/spa'))

app.listen(3030, () => {
  console.log('伺服器已成功運行')
  console.log('-------------------')
  console.log('GUI網頁 => http://localhost:3030')
  console.log('')
  console.log('')
  console.log('RichMenu圖片下載位置 => public/images')
  console.log('-------------------')
})